services:
  next-app:
    build: ./my-app
    container_name: my-next-app
    ports:
      - "3000:3000"
    volumes:
      - ./my-app:/app
      - /app/node_modules

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: youwerehere
      POSTGRES_PASSWORD: youwerehere
      POSTGRES_DB: movie_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8008:8008"
    volumes:
      - ./fastapi:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8008 --reload

volumes:
  postgres_data: